config/routes.rb
Stunable::Application.routes.draw do
  resources :carts

  resources :line_items

  get "store/index"

  resources :products

  get "blog/index"

  resources :blog_posts

  root to: 'blog#index', as: 'blog'

match ':controller(/:action(/:id))(.:format)'
end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base

  attr_accessible :author, :body, :title, :date

# TO VERIFY THAT AUTHOR CREATES A TITLE FOR THE BLOG POST 
  validates_presence_of :body, :title, :author
  
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_filter :authenticate, :except => [ :index, :show ] # requires username and password to add new post
  # GET /blog_posts
  # GET /blog_posts.json
  def index
    @blog_posts = BlogPost.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blog_posts }
    end
  end

  # GET /blog_posts/1
  # GET /blog_posts/1.json
  def show
    @blog_post = BlogPost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @blog_post }
    end
  end

  # GET /blog_posts/new
  # GET /blog_posts/new.json
  def new
    @blog_post = BlogPost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blog_post }
    end
  end

  # GET /blog_posts/1/edit
  def edit
    @blog_post = BlogPost.find(params[:id])
  end

  # POST /blog_posts
  # POST /blog_posts.json
  def create
    @blog_post = BlogPost.new(params[:blog_post])

    respond_to do |format|
      if @blog_post.save
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully created.' }
        format.json { render json: @blog_post, status: :created, location: @blog_post }
      else
        format.html { render action: "new" }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /blog_posts/1
  # PUT /blog_posts/1.json
  def update
    @blog_post = BlogPost.find(params[:id])

    respond_to do |format|
      if @blog_post.update_attributes(params[:blog_post])
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_posts/1
  # DELETE /blog_posts/1.json
  def destroy
    @blog_post = BlogPost.find(params[:id])
    @blog_post.destroy

    respond_to do |format|
      format.html { redirect_to blog_posts_url }
      format.json { head :no_content }
    end
  end

private
  def authenticate # requires username and password to add new post
    authenticate_or_request_with_http_basic do |name, password|
      name == "admin" && password == "Rockin1"
    end
  end

end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/views/blog_posts/_blog_post.html.erb
 <h2><%= link_to_unless_current @post.title, @post %></h2>
 <%= simple_format blog_post.body %>

app/views/blog_posts/_form.html.erb
<%= form_for(@blog_post) do |f| %>
  <% if @blog_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog_post.errors.count, "error") %> prohibited this blog_post from being saved:</h2>

      <ul>
      <% @blog_post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
<!-- DATE  -->
  <div class="field">
    <%= f.label :date %><br />
    <%= f.text_field :date %>
  </div>
<!-- TITLE -->
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
<!-- AUTHOR -->
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>

<!-- BODY -->
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>

  <div class="myButton">
    <%= f.submit "publish" %> 
  </div>


<% end %>

app/views/blog_posts/edit.html.erb
<h1>Edit Blog Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog_post %> |
<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/index.html.erb
<h1>Stunable Blog Admin</h1>

<a href=<%= new_blog_post_path %> class="myButton">+ new post </a>

<br />

<table>
<% @blog_posts.each do |blog_post| %>
  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">

    <td class="list_description">
      <dl>
        <dt> <%= blog_post.date %>  </dt>
        <dt> <%= blog_post.title %> </dt>
        <dt> By <%= blog_post.author %> </dt>
        <dt> <%= blog_post.body %>  </dt>
      </dl>
    </td>

    <td class="list_actions">
      <%= link_to 'Show', blog_post %><br/>
      <%= link_to 'Edit', edit_blog_post_path(blog_post) %><br/>
      <%= link_to 'Destroy', blog_post, method: :delete,
                  data: { confirm: 'Are you sure you want to scrap your blog post?'} %>
    </td>
  </tr>
<% end %>
</table>

app/views/blog_posts/new.html.erb
<h1>Create New Blog Post</h1>

<%= render 'form' %>


<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @blog_post.date %>
</p>

<p>
  <b>Title:</b>
  <%= @blog_post.title %>
</p>

<p>
  <b>Author:</b>
  <%= @blog_post.author %>
</p>

<p>
  <b>Body:</b>
  <%= @blog_post.body %>
</p>


<%= link_to 'Edit', edit_blog_post_path(@blog_post) %> |
<%= link_to 'Back', blog_posts_path %>